services:
  h2:
    image: eclipse-temurin:21-jre-alpine
    container_name: h2
    working_dir: /opt
    command: >
      sh -c "apk add --no-cache wget && \
      wget -qO /tmp/h2.jar https://repo1.maven.org/maven2/com/h2database/h2/2.3.232/h2-2.3.232.jar && \
      java -cp /tmp/h2.jar org.h2.tools.Server -ifNotExists -tcp -tcpAllowOthers -web -webAllowOthers -baseDir /data"
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - h2-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - h2-net
    restart: unless-stopped

volumes:
  h2-data:

networks:
  h2-net:
    driver: bridge
