spring:
  # DATASOURCE
  datasource:
    url: jdbc:h2:file:./data/auth_db
    username: sa
    password: 321
    driver-class-name: org.h2.Driver
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console